image: node:16

stages: # List of stages for jobs, and their order of execution
  - test

unit-test-job: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  before_script:
    - npm install
  script:
    - npm run test
