image: node:16

stages: # List of stages for jobs, and their order of execution
  - test
  - build
  - deploy

unit-test-job: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  before_script:
    - npm install
  script:
    - npm run test

build-job:
  stage: build
  script:
    - npm install
    - npm run build

deploy-job:
  stage: deploy
  needs: [unit-test-job, build-job]
  before_script:
    - apt-get update
    - apt-get install sshpass
    - ssh-keyscan -t rsa test7.exozet.com >> ~/.ssh/known_hosts
  script:
    - npm install
    - npm run build
    - sshpass -p "$DEPLOY_SERVER_KEY" scp -r ./build php@test7.exozet.com:/srv/htdocs/meetmedium/public
